name: 2inf
channels:
    - defaults
dependencies:
    - python=3.12
    - numpy
    - pandas
    - matplotlib
    - tqdm
    - astropy
    - jupyterlab
    - pip
    - pip:
        - vice>=1.3.1
        - dill